# Generated by Django 3.0.4 on 2020-03-17 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_song_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
