# Generated by Django 3.0.4 on 2020-03-24 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_search'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Search',
        ),
    ]
