# Generated by Django 3.0.4 on 2020-03-24 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_song_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='thumbnail_url',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
    ]
